<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-VitalHelse-1dced300-d381-47f8-b85f-3dbe07d81346</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="MailKit" Version="4.14.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="SendGrid" Version="9.29.3" />
        <PackageReference Include="Stripe.net" Version="49.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\css\temp\" />
      <Folder Include="wwwroot\images\products\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Areas\Identity\Pages\Account\Manage\BusinessProfile.cs">
        <DependentUpon>BusinessProfile.cshtml</DependentUpon>
      </Compile>
      <Compile Update="Areas\Identity\Pages\Account\Manage\Address.cs">
        <DependentUpon>Address.cshtml</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Admin\Discount\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Admin\Discount\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Discount\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Discount\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Admin\CategoryDiscount\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Discount\Campaign.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Discount\CategoryDiscount.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Discount\DiscountCodes.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Views\Admin\Discount\Create.cshtml" />
      <UpToDateCheckInput Remove="Views\Admin\Discount\Index.cshtml" />
    </ItemGroup>

</Project>
