using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VitalHelse.Models;

public class ProductDiscount
{
    public int ProductDiscountId { get; set; }

    [Range(0, 100)]
    public double DiscountRate { get; set; } // 15 = 15%

    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }

    public bool IsActive { get; set; } = false;

    public bool IsCategoryDiscount { get; set; } = false;
    public bool IsAutoGenerated { get; set; } = false;

    public int? ProductId { get; set; }
    public Product? Product { get; set; }

    public int? CategoryId { get; set; }
    public Category? Category { get; set; }
}